// Generated by Xata Codegen 0.23.2. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "Product",
    columns: [
      { name: "stripe_id", type: "string", unique: true },
      { name: "active", type: "bool", defaultValue: "true" },
      { name: "default_price", type: "string", unique: true },
      { name: "description", type: "text" },
      {
        name: "name",
        type: "string",
        notNull: true,
        defaultValue: "Product Name",
      },
      { name: "created", type: "datetime" },
      { name: "images", type: "multiple" },
      { name: "livemode", type: "bool", defaultValue: "false" },
      { name: "statement_descriptor", type: "string" },
      { name: "tax_code", type: "string" },
      { name: "updated", type: "datetime" },
      { name: "url", type: "string" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Product = InferredTypes["Product"];
export type ProductRecord = Product & XataRecord;

export type DatabaseSchema = {
  Product: ProductRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://Domitrius-s-workspace-7cu2ck.us-east-1.xata.sh/db/ecommerce-template",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
